# Config.pri file version 2.0. Auto-generated by IDE. Any changes made by user will be lost!
BASEDIR = $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        } else {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }

    }

    CONFIG(release, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

simulator {
    CONFIG(debug, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

config_pri_assets {
    OTHER_FILES += \
        $$quote($$BASEDIR/assets/GenericTab.qml) \
        $$quote($$BASEDIR/assets/MapPage.qml) \
        $$quote($$BASEDIR/assets/PhotoPreviewPage.qml) \
        $$quote($$BASEDIR/assets/about.qml) \
        $$quote($$BASEDIR/assets/attach.qml) \
        $$quote($$BASEDIR/assets/chatUI.qml) \
        $$quote($$BASEDIR/assets/contacts.qml) \
        $$quote($$BASEDIR/assets/emoji.qml) \
        $$quote($$BASEDIR/assets/genericSettings.qml) \
        $$quote($$BASEDIR/assets/help.qml) \
        $$quote($$BASEDIR/assets/html/images/layers-2x.png) \
        $$quote($$BASEDIR/assets/html/images/layers.png) \
        $$quote($$BASEDIR/assets/html/images/marker-icon-2x.png) \
        $$quote($$BASEDIR/assets/html/images/marker-icon.png) \
        $$quote($$BASEDIR/assets/html/images/marker-shadow.png) \
        $$quote($$BASEDIR/assets/html/leaflet-src.esm.js.map) \
        $$quote($$BASEDIR/assets/html/leaflet-src.js.map) \
        $$quote($$BASEDIR/assets/html/leaflet.css) \
        $$quote($$BASEDIR/assets/html/leaflet.js.map) \
        $$quote($$BASEDIR/assets/html/leaflet_js.txt) \
        $$quote($$BASEDIR/assets/html/map.html) \
        $$quote($$BASEDIR/assets/images/bPro.png) \
        $$quote($$BASEDIR/assets/images/channel.png) \
        $$quote($$BASEDIR/assets/images/discord.png) \
        $$quote($$BASEDIR/assets/images/doubleTick.png) \
        $$quote($$BASEDIR/assets/images/download.png) \
        $$quote($$BASEDIR/assets/images/download2.png) \
        $$quote($$BASEDIR/assets/images/facebook.png) \
        $$quote($$BASEDIR/assets/images/googlechat.png) \
        $$quote($$BASEDIR/assets/images/googlemessages.png) \
        $$quote($$BASEDIR/assets/images/ic_attach.png) \
        $$quote($$BASEDIR/assets/images/ic_camera.png) \
        $$quote($$BASEDIR/assets/images/ic_cancel.png) \
        $$quote($$BASEDIR/assets/images/ic_compose.png) \
        $$quote($$BASEDIR/assets/images/ic_contact.png) \
        $$quote($$BASEDIR/assets/images/ic_copy.png) \
        $$quote($$BASEDIR/assets/images/ic_delete.png) \
        $$quote($$BASEDIR/assets/images/ic_doctype_doc.png) \
        $$quote($$BASEDIR/assets/images/ic_doctype_generic.png) \
        $$quote($$BASEDIR/assets/images/ic_doctype_music.png) \
        $$quote($$BASEDIR/assets/images/ic_doctype_picture.png) \
        $$quote($$BASEDIR/assets/images/ic_doctype_video.png) \
        $$quote($$BASEDIR/assets/images/ic_done.png) \
        $$quote($$BASEDIR/assets/images/ic_edit.png) \
        $$quote($$BASEDIR/assets/images/ic_emoji.png) \
        $$quote($$BASEDIR/assets/images/ic_forward.png) \
        $$quote($$BASEDIR/assets/images/ic_gallery.png) \
        $$quote($$BASEDIR/assets/images/ic_group.png) \
        $$quote($$BASEDIR/assets/images/ic_group_white.png) \
        $$quote($$BASEDIR/assets/images/ic_info.png) \
        $$quote($$BASEDIR/assets/images/ic_keyboard.png) \
        $$quote($$BASEDIR/assets/images/ic_location.png) \
        $$quote($$BASEDIR/assets/images/ic_microphone.png) \
        $$quote($$BASEDIR/assets/images/ic_play.png) \
        $$quote($$BASEDIR/assets/images/ic_previous.png) \
        $$quote($$BASEDIR/assets/images/ic_reply.png) \
        $$quote($$BASEDIR/assets/images/ic_search.png) \
        $$quote($$BASEDIR/assets/images/ic_send.png) \
        $$quote($$BASEDIR/assets/images/ic_send.svg) \
        $$quote($$BASEDIR/assets/images/ic_settings.png) \
        $$quote($$BASEDIR/assets/images/ic_share.png) \
        $$quote($$BASEDIR/assets/images/ic_speaker_dk.png) \
        $$quote($$BASEDIR/assets/images/ic_video.png) \
        $$quote($$BASEDIR/assets/images/ic_view_image.png) \
        $$quote($$BASEDIR/assets/images/icon.png) \
        $$quote($$BASEDIR/assets/images/instagram.png) \
        $$quote($$BASEDIR/assets/images/line.png) \
        $$quote($$BASEDIR/assets/images/linkedin.png) \
        $$quote($$BASEDIR/assets/images/matrix.png) \
        $$quote($$BASEDIR/assets/images/mute.png) \
        $$quote($$BASEDIR/assets/images/pin.png) \
        $$quote($$BASEDIR/assets/images/read.png) \
        $$quote($$BASEDIR/assets/images/signal.png) \
        $$quote($$BASEDIR/assets/images/slack.png) \
        $$quote($$BASEDIR/assets/images/telegram.png) \
        $$quote($$BASEDIR/assets/images/tumblr.png) \
        $$quote($$BASEDIR/assets/images/unmute.png) \
        $$quote($$BASEDIR/assets/images/unpin.png) \
        $$quote($$BASEDIR/assets/images/unread.png) \
        $$quote($$BASEDIR/assets/images/wPro.png) \
        $$quote($$BASEDIR/assets/images/whatsapp.png) \
        $$quote($$BASEDIR/assets/images/x.png) \
        $$quote($$BASEDIR/assets/main.qml) \
        $$quote($$BASEDIR/assets/search.qml) \
        $$quote($$BASEDIR/assets/settings.qml)
}

config_pri_source_group1 {
    SOURCES += \
        $$quote($$BASEDIR/src/Database.cpp) \
        $$quote($$BASEDIR/src/LocationSession.cpp) \
        $$quote($$BASEDIR/src/ScreenManager.cpp) \
        $$quote($$BASEDIR/src/applicationui.cpp) \
        $$quote($$BASEDIR/src/main.cpp)

    HEADERS += \
        $$quote($$BASEDIR/src/Database.hpp) \
        $$quote($$BASEDIR/src/LocationSession.hpp) \
        $$quote($$BASEDIR/src/ScreenManager.hpp) \
        $$quote($$BASEDIR/src/applicationui.hpp)
}

CONFIG += precompile_header

PRECOMPILED_HEADER = $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES += \
        $$quote($$BASEDIR/../src/*.c) \
        $$quote($$BASEDIR/../src/*.c++) \
        $$quote($$BASEDIR/../src/*.cc) \
        $$quote($$BASEDIR/../src/*.cpp) \
        $$quote($$BASEDIR/../src/*.cxx) \
        $$quote($$BASEDIR/../assets/*.qml) \
        $$quote($$BASEDIR/../assets/*.js) \
        $$quote($$BASEDIR/../assets/*.qs) \
        $$quote($$BASEDIR/../assets/html/*.qml) \
        $$quote($$BASEDIR/../assets/html/*.js) \
        $$quote($$BASEDIR/../assets/html/*.qs) \
        $$quote($$BASEDIR/../assets/html/images/*.qml) \
        $$quote($$BASEDIR/../assets/html/images/*.js) \
        $$quote($$BASEDIR/../assets/html/images/*.qs) \
        $$quote($$BASEDIR/../assets/images/*.qml) \
        $$quote($$BASEDIR/../assets/images/*.js) \
        $$quote($$BASEDIR/../assets/images/*.qs)

    HEADERS += \
        $$quote($$BASEDIR/../src/*.h) \
        $$quote($$BASEDIR/../src/*.h++) \
        $$quote($$BASEDIR/../src/*.hh) \
        $$quote($$BASEDIR/../src/*.hpp) \
        $$quote($$BASEDIR/../src/*.hxx)
}

TRANSLATIONS = $$quote($${TARGET}.ts)
